### ISSUE TITLE
Won't work

### ISSUE THREAD

**Issue by GRIMMYY** [Kyle2000/Server-Nuker#1]
I opened the file and I can't get anything to work

I installed everything and opened it but idk how to get it to work

**Comment by LeDBansSpy** [comment]
![image](https://user-images.githubusercontent.com/33135522/32074772-78228fec-ba68-11e7-9fdb-5fedb0767540.png)
hes trying to waste you time lol dont listen

**Comment by GRIMMYY** [comment]
it wouldn't surprise me if your new account gets deleted too ;)

**Comment by GRIMMYY** [comment]
yet you left this open too? xD

**Comment by GRIMMYY** [comment]
Lol nice Kyle
