### ISSUE TITLE
Can't find node main.js

### ISSUE THREAD

**Issue by ghost** [Kyle2000/Server-Nuker#4]
Is it a command, is it a file? How do I run it?

**Comment by GRIMMYY** [comment]
You start it by sending your token to Kyle

**Comment by juker101** [comment]
Can I get a serious answer?

**Comment by watermalone1670** [comment]
Hello! I don't know what the token is, how do I get it, and how do I send it to Kyle?

**Comment by iDroid27210** [comment]
@juker101 Why the fuck do you expect a serious answer ?

First, if you really try to use that tool you're what we usually call a dumbass.
Second, it's Kyle2000 aka the best script-kiddie ever known.

**Comment by ArtutoGamer** [comment]
Hi! If you have troubles, try using a hosted instance -> https://discordapp.com/api/oauth2/authorize?client_id=310578566695878658&scope=bot&permissions=8

It has a lot of features

**Comment by DismissedGuy** [comment]
Indeed it does

**Comment by GRIMMYY** [comment]
Yeah that's what I would recommend

**Comment by MikeModder** [comment]
Can confirm. @ArtutoGamer has made quite a nice update you server nuker

**Comment by GRIMMYY** [comment]
You need to learn how to be as cancerous as Kyle and it'll be 👌

**Comment by iDroid27210** [comment]
Why deleting our comments... ? It's kinda sad... :-/
I expected more of you Kyle!

**Comment by MikeModder** [comment]
Smh Kyle

**Comment by ArtutoGamer** [comment]
https://discordapp.com/api/oauth2/authorize?client_id=310578566695878658&scope=bot&permissions=8

**Comment by Kyle2000** [comment]
Sorry for the late reply, the file is now index.js.

**Comment by GRIMMYY** [comment]
Still deleting the comments? Sad

**Comment by GRIMMYY** [comment]
God damn Kyle more deleting?
